/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in many projects and is committed here so
// TypeScript resolves Next types before the first local dev start.
